//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.15 at 01:39:48 PM KST 
//


package org.oliot.model.tracTrace;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ScopeInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "ScopeInformation");
    private final static QName _CorrelationInformation_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "CorrelationInformation");
    private final static QName _StandardBusinessDocumentHeader_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocumentHeader");
    private final static QName _BusinessService_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "BusinessService");
    private final static QName _StandardBusinessDocument_QNAME = new QName("http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", "StandardBusinessDocument");
    private final static QName _EPCISDocument_QNAME = new QName("axis.epcis.oliot.org", "EPCISDocument");
    private final static QName _EventListTypeExtension_QNAME = new QName("", "extension");
    private final static QName _EventListTypeTransactionEvent_QNAME = new QName("", "TransactionEvent");
    private final static QName _EventListTypeObjectEvent_QNAME = new QName("", "ObjectEvent");
    private final static QName _EventListTypeQuantityEvent_QNAME = new QName("", "QuantityEvent");
    private final static QName _EventListTypeAggregationEvent_QNAME = new QName("", "AggregationEvent");
    private final static QName _EventListTypeSensorEvent_QNAME = new QName("", "SensorEvent");
    private final static QName _EventListTypeTransformationEvent_QNAME = new QName("", "TransformationEvent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EPCISDocument }
     * 
     */
    public EPCISDocument createEPCISDocumentType() {
        return new EPCISDocument();
    }

    /**
     * Create an instance of {@link EPCISHeaderExtensionType }
     * 
     */
    public EPCISHeaderExtensionType createEPCISHeaderExtensionType() {
        return new EPCISHeaderExtensionType();
    }

    /**
     * Create an instance of {@link SourceDestType }
     * 
     */
    public SourceDestType createSourceDestType() {
        return new SourceDestType();
    }

    /**
     * Create an instance of {@link BusinessTransaction }
     * 
     */
    public BusinessTransaction createBusinessTransactionType() {
        return new BusinessTransaction();
    }

    /**
     * Create an instance of {@link TransactionEventExtensionType }
     * 
     */
    public TransactionEventExtensionType createTransactionEventExtensionType() {
        return new TransactionEventExtensionType();
    }

    /**
     * Create an instance of {@link EPCISEventListExtensionType }
     * 
     */
    public EPCISEventListExtensionType createEPCISEventListExtensionType() {
        return new EPCISEventListExtensionType();
    }

    /**
     * Create an instance of {@link ObjectEventExtension2Type }
     * 
     */
    public ObjectEventExtension2Type createObjectEventExtension2Type() {
        return new ObjectEventExtension2Type();
    }

    /**
     * Create an instance of {@link BusinessLocationExtension }
     * 
     */
    public BusinessLocationExtension createBusinessLocationExtensionType() {
        return new BusinessLocationExtension();
    }

    /**
     * Create an instance of {@link ILMDExtension }
     * 
     */
    public ILMDExtension createILMDExtensionType() {
        return new ILMDExtension();
    }

    /**
     * Create an instance of {@link EPCISEventListExtension2Type }
     * 
     */
    public EPCISEventListExtension2Type createEPCISEventListExtension2Type() {
        return new EPCISEventListExtension2Type();
    }

    /**
     * Create an instance of {@link SensorEvent }
     * 
     */
    public SensorEvent createSensorEventType() {
        return new SensorEvent();
    }

    /**
     * Create an instance of {@link SourceList }
     * 
     */
    public SourceList createSourceListType() {
        return new SourceList();
    }

    /**
     * Create an instance of {@link QuantityEvent }
     * 
     */
    public QuantityEvent createQuantityEventType() {
        return new QuantityEvent();
    }

    /**
     * Create an instance of {@link SensorEventExtensionType }
     * 
     */
    public SensorEventExtensionType createSensorEventExtensionType() {
        return new SensorEventExtensionType();
    }

    /**
     * Create an instance of {@link EPCISDocumentExtensionType }
     * 
     */
    public EPCISDocumentExtensionType createEPCISDocumentExtensionType() {
        return new EPCISDocumentExtensionType();
    }

    /**
     * Create an instance of {@link QuantityEventExtensionType }
     * 
     */
    public QuantityEventExtensionType createQuantityEventExtensionType() {
        return new QuantityEventExtensionType();
    }

    /**
     * Create an instance of {@link SensingList }
     * 
     */
    public SensingList createSensingListType() {
        return new SensingList();
    }

    /**
     * Create an instance of {@link ReadPoint }
     * 
     */
    public ReadPoint createReadPointType() {
        return new ReadPoint();
    }

    /**
     * Create an instance of {@link AggregationEvent }
     * 
     */
    public AggregationEvent createAggregationEventType() {
        return new AggregationEvent();
    }

    /**
     * Create an instance of {@link EPCISHeader }
     * 
     */
    public EPCISHeader createEPCISHeaderType() {
        return new EPCISHeader();
    }

    /**
     * Create an instance of {@link TransformationEvent }
     * 
     */
    public TransformationEvent createTransformationEventType() {
        return new TransformationEvent();
    }

    /**
     * Create an instance of {@link EPCISBody }
     * 
     */
    public EPCISBody createEPCISBodyType() {
        return new EPCISBody();
    }

    /**
     * Create an instance of {@link AggregationEventExtension2 }
     * 
     */
    public AggregationEventExtension2 createAggregationEventExtension2Type() {
        return new AggregationEventExtension2();
    }

    /**
     * Create an instance of {@link EventList }
     * 
     */
    public EventList createEventListType() {
        return new EventList();
    }

    /**
     * Create an instance of {@link ILMDType }
     * 
     */
    public ILMDType createILMDType() {
        return new ILMDType();
    }

    /**
     * Create an instance of {@link EPCList }
     * 
     */
    public EPCList createEPCListType() {
        return new EPCList();
    }

    /**
     * Create an instance of {@link SensingElement }
     * 
     */
    public SensingElement createSensingElementType() {
        return new SensingElement();
    }

    /**
     * Create an instance of {@link DestinationList }
     * 
     */
    public DestinationList createDestinationListType() {
        return new DestinationList();
    }

    /**
     * Create an instance of {@link ObjectEventExtensionType }
     * 
     */
    public ObjectEventExtensionType createObjectEventExtensionType() {
        return new ObjectEventExtensionType();
    }

    /**
     * Create an instance of {@link EPCISBodyExtensionType }
     * 
     */
    public EPCISBodyExtensionType createEPCISBodyExtensionType() {
        return new EPCISBodyExtensionType();
    }

    /**
     * Create an instance of {@link TransactionEvent }
     * 
     */
    public TransactionEvent createTransactionEventType() {
        return new TransactionEvent();
    }

    /**
     * Create an instance of {@link QuantityListType }
     * 
     */
    public QuantityListType createQuantityListType() {
        return new QuantityListType();
    }

    /**
     * Create an instance of {@link EPCISEventExtensionType }
     * 
     */
    public EPCISEventExtensionType createEPCISEventExtensionType() {
        return new EPCISEventExtensionType();
    }

    /**
     * Create an instance of {@link TransactionEventExtension2Type }
     * 
     */
    public TransactionEventExtension2Type createTransactionEventExtension2Type() {
        return new TransactionEventExtension2Type();
    }

    /**
     * Create an instance of {@link ReadPointExtensionType }
     * 
     */
    public ReadPointExtensionType createReadPointExtensionType() {
        return new ReadPointExtensionType();
    }

    /**
     * Create an instance of {@link ObjectEvent }
     * 
     */
    public ObjectEvent createObjectEventType() {
        return new ObjectEvent();
    }

    /**
     * Create an instance of {@link QuantityElement }
     * 
     */
    public QuantityElement createQuantityElementType() {
        return new QuantityElement();
    }

    /**
     * Create an instance of {@link TransformationEventExtensionType }
     * 
     */
    public TransformationEventExtensionType createTransformationEventExtensionType() {
        return new TransformationEventExtensionType();
    }

    /**
     * Create an instance of {@link BusinessLocation }
     * 
     */
    public BusinessLocation createBusinessLocationType() {
        return new BusinessLocation();
    }

    /**
     * Create an instance of {@link BusinessTransactionList }
     * 
     */
    public BusinessTransactionList createBusinessTransactionListType() {
        return new BusinessTransactionList();
    }

    /**
     * Create an instance of {@link AggregationEventExtension }
     * 
     */
    public AggregationEventExtension createAggregationEventExtensionType() {
        return new AggregationEventExtension();
    }

    /**
     * Create an instance of {@link EPC }
     * 
     */
    public EPC createEPC() {
        return new EPC();
    }

    /**
     * Create an instance of {@link StandardBusinessDocumentHeader }
     * 
     */
    public StandardBusinessDocumentHeader createStandardBusinessDocumentHeader() {
        return new StandardBusinessDocumentHeader();
    }

    /**
     * Create an instance of {@link CorrelationInformation }
     * 
     */
    public CorrelationInformation createCorrelationInformation() {
        return new CorrelationInformation();
    }

    /**
     * Create an instance of {@link StandardBusinessDocument }
     * 
     */
    public StandardBusinessDocument createStandardBusinessDocument() {
        return new StandardBusinessDocument();
    }

    /**
     * Create an instance of {@link BusinessService }
     * 
     */
    public BusinessService createBusinessService() {
        return new BusinessService();
    }

    /**
     * Create an instance of {@link ManifestItem }
     * 
     */
    public ManifestItem createManifestItem() {
        return new ManifestItem();
    }

    /**
     * Create an instance of {@link ServiceTransaction }
     * 
     */
    public ServiceTransaction createServiceTransaction() {
        return new ServiceTransaction();
    }

    /**
     * Create an instance of {@link ContactInformation }
     * 
     */
    public ContactInformation createContactInformation() {
        return new ContactInformation();
    }

    /**
     * Create an instance of {@link Manifest }
     * 
     */
    public Manifest createManifest() {
        return new Manifest();
    }

    /**
     * Create an instance of {@link DocumentIdentification }
     * 
     */
    public DocumentIdentification createDocumentIdentification() {
        return new DocumentIdentification();
    }

    /**
     * Create an instance of {@link PartnerIdentification }
     * 
     */
    public PartnerIdentification createPartnerIdentification() {
        return new PartnerIdentification();
    }

    /**
     * Create an instance of {@link Partner }
     * 
     */
    public Partner createPartner() {
        return new Partner();
    }

    /**
     * Create an instance of {@link BusinessScope }
     * 
     */
    public BusinessScope createBusinessScope() {
        return new BusinessScope();
    }

    /**
     * Create an instance of {@link Scope }
     * 
     */
    public Scope createScope() {
        return new Scope();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "ScopeInformation")
    public JAXBElement<Object> createScopeInformation(Object value) {
        return new JAXBElement<Object>(_ScopeInformation_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorrelationInformation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "CorrelationInformation", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<CorrelationInformation> createCorrelationInformation(CorrelationInformation value) {
        return new JAXBElement<CorrelationInformation>(_CorrelationInformation_QNAME, CorrelationInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocumentHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocumentHeader")
    public JAXBElement<StandardBusinessDocumentHeader> createStandardBusinessDocumentHeader(StandardBusinessDocumentHeader value) {
        return new JAXBElement<StandardBusinessDocumentHeader>(_StandardBusinessDocumentHeader_QNAME, StandardBusinessDocumentHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "BusinessService", substitutionHeadNamespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", substitutionHeadName = "ScopeInformation")
    public JAXBElement<BusinessService> createBusinessService(BusinessService value) {
        return new JAXBElement<BusinessService>(_BusinessService_QNAME, BusinessService.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardBusinessDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", name = "StandardBusinessDocument")
    public JAXBElement<StandardBusinessDocument> createStandardBusinessDocument(StandardBusinessDocument value) {
        return new JAXBElement<StandardBusinessDocument>(_StandardBusinessDocument_QNAME, StandardBusinessDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "axis.epcis.oliot.org", name = "EPCISDocument")
    public JAXBElement<EPCISDocument> createEPCISDocument(EPCISDocument value) {
        return new JAXBElement<EPCISDocument>(_EPCISDocument_QNAME, EPCISDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EPCISEventListExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extension", scope = EventList.class)
    public JAXBElement<EPCISEventListExtensionType> createEventListTypeExtension(EPCISEventListExtensionType value) {
        return new JAXBElement<EPCISEventListExtensionType>(_EventListTypeExtension_QNAME, EPCISEventListExtensionType.class, EventList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransactionEvent", scope = EventList.class)
    public JAXBElement<TransactionEvent> createEventListTypeTransactionEvent(TransactionEvent value) {
        return new JAXBElement<TransactionEvent>(_EventListTypeTransactionEvent_QNAME, TransactionEvent.class, EventList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ObjectEvent", scope = EventList.class)
    public JAXBElement<ObjectEvent> createEventListTypeObjectEvent(ObjectEvent value) {
        return new JAXBElement<ObjectEvent>(_EventListTypeObjectEvent_QNAME, ObjectEvent.class, EventList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantityEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "QuantityEvent", scope = EventList.class)
    public JAXBElement<QuantityEvent> createEventListTypeQuantityEvent(QuantityEvent value) {
        return new JAXBElement<QuantityEvent>(_EventListTypeQuantityEvent_QNAME, QuantityEvent.class, EventList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AggregationEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AggregationEvent", scope = EventList.class)
    public JAXBElement<AggregationEvent> createEventListTypeAggregationEvent(AggregationEvent value) {
        return new JAXBElement<AggregationEvent>(_EventListTypeAggregationEvent_QNAME, AggregationEvent.class, EventList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SensorEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SensorEvent", scope = EventList.class)
    public JAXBElement<SensorEvent> createEventListTypeSensorEvent(SensorEvent value) {
        return new JAXBElement<SensorEvent>(_EventListTypeSensorEvent_QNAME, SensorEvent.class, EventList.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformationEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TransformationEvent", scope = EventList.class)
    public JAXBElement<TransformationEvent> createEventListTypeTransformationEvent(TransformationEvent value) {
        return new JAXBElement<TransformationEvent>(_EventListTypeTransformationEvent_QNAME, TransformationEvent.class, EventList.class, value);
    }

}
