//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.23 at 08:16:54 PM KST 
//

package org.oliot.model.tracTrace;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.springframework.data.mongodb.core.mapping.Document;
import org.w3c.dom.Element;

/**
 * 
 * Object Event captures information about an event pertaining to one or more
 * objects identified by EPCs.
 * 
 * 
 * <p>
 * Java class for ObjectEventType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ObjectEventType">
 *   &lt;complexContent>
 *     &lt;extension base="{axis.epcis.oliot.org}EPCISEventType">
 *       &lt;sequence>
 *         &lt;element name="epcList" type="{axis.epcis.oliot.org}EPCListType"/>
 *         &lt;element name="action" type="{axis.epcis.oliot.org}ActionType"/>
 *         &lt;element name="bizStep" type="{axis.epcis.oliot.org}BusinessStepIDType" minOccurs="0"/>
 *         &lt;element name="disposition" type="{axis.epcis.oliot.org}DispositionIDType" minOccurs="0"/>
 *         &lt;element name="readPoint" type="{axis.epcis.oliot.org}ReadPointType" minOccurs="0"/>
 *         &lt;element name="bizLocation" type="{axis.epcis.oliot.org}BusinessLocationType" minOccurs="0"/>
 *         &lt;element name="bizTransactionList" type="{axis.epcis.oliot.org}BusinessTransactionListType" minOccurs="0"/>
 *         &lt;element name="ilmd" type="{axis.epcis.oliot.org}ILMDType" minOccurs="0"/>
 *         &lt;element name="extension" type="{axis.epcis.oliot.org}ObjectEventExtensionType" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectEventType", propOrder = { "epcList", "action",
		"bizStep", "disposition", "readPoint", "bizLocation",
		"bizTransactionList", "ilmd", "extension", "any" })
@Document(collection = "ObjectEvent")
public class ObjectEvent extends EPCISEvent {

	@XmlElement(required = true)
	protected EPCList epcList;
	@XmlElement(required = true)
	protected Action action;
	protected String bizStep;

	protected String disposition;
	protected ReadPoint readPoint;
	protected BusinessLocation bizLocation;
	protected BusinessTransactionList bizTransactionList;
	protected ILMDType ilmd;
	
	protected ObjectEventExtensionType extension;
	@XmlAnyElement(lax = true)
	protected List<Object> any;

	public void setAny(List<Object> any) {
		this.any = any;
	}

	/**
	 * Gets the value of the epcList property.
	 * 
	 * @return possible object is {@link EPCList }
	 * 
	 */
	public EPCList getEpcList() {
		return epcList;
	}

	/**
	 * Sets the value of the epcList property.
	 * 
	 * @param value
	 *            allowed object is {@link EPCList }
	 * 
	 */
	public void setEpcList(EPCList value) {
		this.epcList = value;
	}

	/**
	 * Gets the value of the action property.
	 * 
	 * @return possible object is {@link Action }
	 * 
	 */
	public Action getAction() {
		return action;
	}

	/**
	 * Sets the value of the action property.
	 * 
	 * @param value
	 *            allowed object is {@link Action }
	 * 
	 */
	public void setAction(Action value) {
		this.action = value;
	}

	/**
	 * Gets the value of the bizStep property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBizStep() {
		return bizStep;
	}

	/**
	 * Sets the value of the bizStep property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBizStep(String value) {
		this.bizStep = value;
	}

	/**
	 * Gets the value of the disposition property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDisposition() {
		return disposition;
	}

	/**
	 * Sets the value of the disposition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDisposition(String value) {
		this.disposition = value;
	}

	/**
	 * Gets the value of the readPoint property.
	 * 
	 * @return possible object is {@link ReadPoint }
	 * 
	 */
	public ReadPoint getReadPoint() {
		return readPoint;
	}

	/**
	 * Sets the value of the readPoint property.
	 * 
	 * @param value
	 *            allowed object is {@link ReadPoint }
	 * 
	 */
	public void setReadPoint(ReadPoint value) {
		this.readPoint = value;
	}

	/**
	 * Gets the value of the bizLocation property.
	 * 
	 * @return possible object is {@link BusinessLocation }
	 * 
	 */
	public BusinessLocation getBizLocation() {
		return bizLocation;
	}

	/**
	 * Sets the value of the bizLocation property.
	 * 
	 * @param value
	 *            allowed object is {@link BusinessLocation }
	 * 
	 */
	public void setBizLocation(BusinessLocation value) {
		this.bizLocation = value;
	}

	/**
	 * Gets the value of the bizTransactionList property.
	 * 
	 * @return possible object is {@link BusinessTransactionList }
	 * 
	 */
	public BusinessTransactionList getBizTransactionList() {
		return bizTransactionList;
	}

	/**
	 * Sets the value of the bizTransactionList property.
	 * 
	 * @param value
	 *            allowed object is {@link BusinessTransactionList }
	 * 
	 */
	public void setBizTransactionList(BusinessTransactionList value) {
		this.bizTransactionList = value;
	}

	/**
	 * Gets the value of the ilmd property.
	 * 
	 * @return possible object is {@link ILMDType }
	 * 
	 */
	public ILMDType getIlmd() {
		return ilmd;
	}

	/**
	 * Sets the value of the ilmd property.
	 * 
	 * @param value
	 *            allowed object is {@link ILMDType }
	 * 
	 */
	public void setIlmd(ILMDType value) {
		this.ilmd = value;
	}

	/**
	 * Gets the value of the extension property.
	 * 
	 * @return possible object is {@link ObjectEventExtensionType }
	 * 
	 */
	public ObjectEventExtensionType getExtension() {
		return extension;
	}

	/**
	 * Sets the value of the extension property.
	 * 
	 * @param value
	 *            allowed object is {@link ObjectEventExtensionType }
	 * 
	 */
	public void setExtension(ObjectEventExtensionType value) {
		this.extension = value;
	}

	/**
	 * Gets the value of the any property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the any property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAny().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Object }
	 * {@link Element }
	 * 
	 * 
	 */
	public List<Object> getAny() {
		if (any == null) {
			any = new ArrayList<Object>();
		}
		return this.any;
	}

	

}
